config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions

  resources :movies do
    resources :reviews, only: [:new, :create]
    resources :favorites, only: [:create]
  end

  resources :reviews, except: [:new, :create]
  resources :favorites, except: [:create]

  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates_uniqueness_of :user_id, scope: :movie_id

  belongs_to :user
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates_presence_of :genre, :title, :year, :director, :cast, :plot

  has_many :favorites
  has_many :reviews
  has_many :fans, through: :favorites, source: :user

  def average_rating
    sum = 0
    self.reviews.each { |review| sum += review.rating }
    sum.to_f / self.reviews.count
  end
end

app/models/review.rb
class Review < ApplicationRecord
  validates_presence_of :rating
  validates_inclusion_of :rating, in: 1..5, message: "must be a number from 1-5"
  validates_uniqueness_of :user_id, scope: :movie_id

  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :username, :email, presence: true, uniqueness: true
  validates_format_of :email, with: EMAIL_REGEX, on: :create
  validates_length_of :password, in: 6..20, on: :create

  has_many :reviews
  has_many :favorites
  has_many :favorite_movies, through: :favorites, source: :movie
  has_many :reviewed_movies, through: :reviews, source: :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to new_session_path unless logged_in?
  end

  def authorized?(resource)
    resource.user == current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_login

  def create
    @movie = Movie.find(params[:movie_id])
    favorite = @movie.favorites.new
    favorite.user = current_user
    favorite.save
    redirect_to @movie
  end

  def destroy
    favorite = Favorite.find(params[:id])
    @movie = favorite.movie
    if authorized?(favorite)
      favorite.destroy
    end
    redirect_to @movie
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.where(genre: params[:genre]).paginate(page: params[:page], per_page: 30)
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_movie_for_review, only: [:new, :create]
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :require_login

  def new
    @review = Review.new
  end

  def create
    @review = @movie.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to @movie
    else
      @errors = @review.errors.full_messages
      render 'new'
    end
  end

  def edit
    redirect_to movie_path(@review.movie) unless authorized?(@review)
  end

  def update
    if authorized?(@review)
      if @review.update(review_params)
        redirect_to movie_path(@review.movie)
      else
        @errors = @review.errors.full_messages
        render 'edit'
      end
    else
      redirect_to movie_path(@review.movie)
    end
  end

  def destroy
    if authorized?(@review)
      @review.destroy
    end
    redirect_to movie_path(@review.movie)
  end

  private
    def find_movie_for_review
      @movie = Movie.find(params[:movie_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:session][:username])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to movies_path
    else
      @errors = ["The username and password you entered do not match."]
      render 'new'
    end
  end

  def destroy
    session.clear
    redirect_to movies_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path
    else
      @errors = @user.errors.full_messages
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Getflicks</title>
    <%= csrf_meta_tags %>

    <!-- Compiled and minified CSS -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
     <%= stylesheet_link_tag    'application', media: 'all' %>

     <%= javascript_include_tag 'application' %>
     <!-- Compiled and minified JavaScript -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper indigo lighten-1">
        <a href="/" class="brand-logo">Getflicks</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if logged_in? %>
            <li><%= link_to "#{current_user.username}", user_path(current_user) %></li>
            <li><%= link_to "Log Out", session_path(session), method: :delete %></li>
          <% else %>
            <li><%= link_to "Register", new_user_path %></li>
            <li><%= link_to "Log In", new_session_path %></li>
          <% end %>
          <li><%= link_to "Home", root_path %></li>
        </ul>
      </div>
    </nav>
    <main class="main">
      <%= yield %>
    </main>
    <footer class="page-footer indigo lighten-1">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text"></h5>
            <p class="grey-text text-lighten-4">An IMDB clone coded at Dev Bootcamp.</p>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
          © 2016 Code by Arshdeep Singh, Evan Renaud, Melanie Gershman, and Sherianne Bolling
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container" >
  <h1>Welcome to Getflicks!</h1>
  <h2>Search by genre:</h2>
  <%= form_tag("/", method: "get") do %>
    <%= label_tag(:genre, "Please capitalize the first letter of genre you search for:") %>
    <%= text_field_tag(:genre) %>
    <p class="waves-effect waves-light white-text btn indigo lighten-1"><%= submit_tag("Search") %></p>
  <% end %>

  <% if @movies.any? %>
    <h2>Here is a list of movies:</h2>
    <div class="carousel">
    <% @movies.each do |movie| %>
      <ul>
        <li><%= link_to image_tag(movie.poster), movie_path(movie), class: "carousel-item" %></li>
      </ul>
    <% end %>
    </div>
  <% end %>
  <p class="paginated-links"><%= will_paginate %></p>
</div>

app/views/movies/show.html.erb
<div class="container">
  <h2><%= @movie.title %></h2>
  <% if @movie.poster != "N/A" %>
    <div class="">
      <%= image_tag(@movie.poster)%>
    </div>
  <% end %>
  <p>Genre: <%= @movie.genre %></p>
  <p>Plot: <%= @movie.plot %></p>
  <p>Director: <%= @movie.director %></p>
  <p>Cast: <%= @movie.cast %></p>
  <p>Year: <%= @movie.year %></p>
  <p>Number of favorites: <%= @movie.favorites.count %></p>
</div>

<div class="review-container container">
  <% if @movie.reviews.any? %>
    <h3>Reviews:</h3>
    <% @movie.reviews.each do |review| %>
      <p> <span>Rating: <%= review.rating %></span> | <%= review.comment %> | Reviewed by <%= link_to "#{review.user.username}", user_path(review.user) %></p>
      <% if review.user == current_user %>
        <%= link_to "Edit Review", edit_review_path(review) %>
        <%= link_to "Delete Review", review_path(review), method: :delete %>
      <% end %>
    <% end %>
    <p>Average Rating: <%= @movie.average_rating %></p>
  <% end %>

  <% if logged_in? %>
    <% if current_user.favorite_movies.exists?(@movie) %>
      <%= link_to 'Unfavorite', favorite_path(@movie.favorites.find_by(user: current_user)), class: "waves-effect waves-light white-text btn indigo lighten-1", method: :delete %>
    <% else %>
      <%= form_for([@movie, @movie.favorites.build]) do |f| %>
        <p class="waves-effect waves-light white-text btn indigo lighten-1">
          <%= f.submit "Favorite" %>
        </p>
      <% end %>
    <% end %></br>
    <% unless current_user.reviewed_movies.exists?(@movie) %>
      <%= link_to "New Review", new_movie_review_path(@movie), class: "waves-effect waves-light white-text btn indigo lighten-1" %>
    <% end %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="container">
  <h2>Edit Review</h2>

  <% if @errors %>
    <div id="error_explanation">
      <p>
        <strong><%= pluralize(@errors.count, "error") %> prohibited this review from being saved:</strong>
      </p>
      <ul>
        <% @errors.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @review do |f| %>
    <p>
      <%= f.label :rating %>
      <%= f.text_field :rating %>
    </p>
    <p>
      <%= f.label :comment %>
      <%= f.text_area :comment %>
    </p>
    <p>
      <%= f.submit "Edit review" %>
    </p>
  <% end %>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h2>New Review</h2>

  <% if @errors %>
    <div id="error_explanation">
      <p>
        <strong><%= pluralize(@errors.count, "error") %> prohibited this review from being saved:</strong>
      </p>
      <ul>
        <% @errors.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @review, url: movie_reviews_path(@movie) do |f| %>
    <p>
      <%= f.label :rating %>
      <%= f.text_field :rating %>
    </p>
    <p>
      <%= f.label :comment %>
      <%= f.text_area :comment %>
    </p>
    <p class="waves-effect waves-light white-text btn indigo lighten-1">
      <%= f.submit "Add review" %>
    </p>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <h2>Create an Account</h2>

  <% if @errors %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@errors.count, "error") %> prohibited account creation:
      </h2>
      <ul>
        <% @errors.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for :user, url: users_path do |f| %>
    <p>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </p>
    <p>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </p>
    <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2><%= @user.username %></h2>
  <% if @user.favorite_movies.any? %>
    <h3>Favorite movies:</h3>
    <ul>
      <% @user.favorite_movies.each do |movie| %>
        <li><%= link_to "#{movie.title}", movie_path(movie) %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div class = "container">
  <% if @user.reviews.any? %>
    <h3>Movies Reviewed:</h3>
    <% @user.reviews.each do |review| %>
      <p><%= link_to "#{review.movie.title}", movie_path(review.movie) %></p>
      <p><span><%= review.rating %></span> | <%= review.comment %></p>
    <% end %>
  <% end %>
</div>